### ISSUE TITLE
how can i only test my test dataset 

### ISSUE THREAD

**Issue by wenxin06133** [jlianglab/BenchmarkTransformers#4]
May I ask how do I store the weights of my training and only run the test set, because every time if the test set is different, it seems that I have to do the training again

**Comment by wenxin06133** [comment]
I want to ask another question, will your code normalize the images to 224X224?

**Comment by Mda233** [comment]
>> May I ask how do I store the weights of my training and only run the test set

You can use the parameter "_--mode test_" in main_classification.py when you want to test only.

>> will your code normalize the images to 224X224?

Yes, the image will be resize to 224X224 by default augmentation.
