### ISSUE TITLE
ark6_teacher_ep200_swinb_projector1376_mlp.pth.tar 

### ISSUE THREAD

**Issue by ZhangRan24** [jlianglab/BenchmarkTransformers#7]
where can I download this file? Ark6_teacher_ep200_swind_projector1376_mlp. pth. tar

**Comment by Mda233** [comment]
Hi, 

Please check this repo: https://github.com/jlianglab/Ark. You can request the model downloading link through this [Google Form](https://forms.gle/qkoDGXNiKRPTDdCe8) or [wjx.cn](https://www.wjx.cn/vm/OvwfYFx.aspx#).

**Comment by ZhangRan24** [comment]
Thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jlianglab/BenchmarkTransformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月3日(星期三) 中午1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jlianglab/BenchmarkTransformers] ark6_teacher_ep200_swinb_projector1376_mlp.pth.tar  (Issue #7)





 
Hi,
 
Please check this repo. You can request the model downloading link through this Google Form or wjx.cn.
